call build_example abs
call build_example bin2int
call build_example digit2text
call build_example div
call build_example exp
call build_example factorial
call build_example fibonacci
call build_example hex2int
call build_example mul
call build_example recursive_fibonacci
call build_example recursive_strcmp
call build_example reverse
call build_example sample
call build_example sqrt
call build_example strlen
call build_example strncmp
call build_example strstr
call build_example strtrim
call build_example strxxx
call build_example toupper
call build_example toupper_str
